#!/bin/sh
# H9 — Generate runtime environment config from Docker environment variables.
# This script runs before nginx starts (nginx entrypoint.d/).

API_URL="${API_URL:-http://localhost:80}"
WS_URL="${WS_URL:-ws://localhost:8080}"

cat > /usr/share/nginx/html/assets/env.js <<EOF
// Auto-generated by docker/frontend/generate-env.sh — do not edit manually.
window.__env = {
  apiUrl: '${API_URL}',
  wsUrl: '${WS_URL}'
};
EOF

echo "[env] Generated /usr/share/nginx/html/assets/env.js"
echo "[env]   apiUrl = ${API_URL}"
echo "[env]   wsUrl  = ${WS_URL}"
